config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :chat_rooms, only: [:new, :create, :show, :index, :update, :edit, :destroy]

  resources :users, only: [:index]

  resources :participants, only: [:create, :destroy]

  resources :charts, only: [:index]

  resources :charts, only: [] do
    collection do
      get 'users_by_chat'
      get 'popular_users'
      get 'current_day_messages'
    end
  end

  #post 'participants' => 'participants#create', as: :create_participant

  mount ActionCable.server => '/cable'

  root 'chat_rooms#index'
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :participants
  has_many :users, through: :participants
  has_many :messages, dependent: :destroy

  validates :title, presence: true, allow_blank: true
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.joins(:participants).where('participants.user_id' => current_user.id.to_s).distinct.order('chat_rooms.updated_at DESC')
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create

    @chat_room = current_user.chat_rooms.build(chat_room_params)

    @chat_room.title = build_title

    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end

  end

  def edit
    @chat_room = ChatRoom.find params[:id]
  end

  def update

    @chat_room = ChatRoom.find params[:id]

    params[:chat_room][:title] = build_title

    if @chat_room.update(chat_room_params)
      flash[:success] = 'Chat room modified!'
      redirect_to chat_room_path
    else
      render 'edit'
    end

  end

  def show
    @chat_room = ChatRoom.includes(:messages).joins(:participants).includes(:users).find_by('chat_rooms.id' => params[:id], 'participants.user_id' => current_user.id.to_s)
    if @chat_room != nil
      @message = Message.new
    else
      not_found
    end
  end

  def destroy

    @chat_room = ChatRoom.find params[:id]

    if @chat_room.destroy
      redirect_to chat_rooms_path
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title, :user_ids => [])
  end

  def build_title #if the user doenst type a title it be build with the participant's names
    if params[:chat_room][:title].blank? || params[:chat_room][:title] == '' || params[:chat_room][:title] == nil
      title = ''
      @chat_room.user_ids.each do |iduser|
        @user = User.find(iduser)
        title += @user.name + ' '
      end
      title
    else
      params[:chat_room][:title]
    end
  end
end

app/views/chat_rooms/_chat_room.html.erb
<li>
  <%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %> </br>
  <% if chat_room.messages.exists? %>
      <p class='text-muted'><%= chat_room.messages.last.body.truncate(50) %></p>
  <% end %>
</li>

app/views/chat_rooms/_form.html.erb
<%= form_for @chat_room do |f| %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: 'form-control' %>
      <%- if @chat_room.errors[:title].any? %>
      <span class="badge bg-danger">
        <%= @chat_room.errors[:title].first %>
      </span>
      <% end %>
    </div>

    <%= hidden_field_tag 'chat_room[user_ids][]', current_user.id %>
    <%= f.label 'Add some Users' %>
    <% User.all.each do |user| %>
        <% if user.id != current_user.id %>
            <div class="form-group">
              <%= check_box_tag 'chat_room[user_ids][]', user.id, @chat_room.user_ids.include?(user.id), id: dom_id(user) %>
              <%= label_tag dom_id(user), user.name %>
            </div>
        <% end %>
    <% end %>

    <%= f.submit 'Save!', class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/edit.html.erb
<h1>Edit chat room</h1>

<%= render 'form' %>

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
  <% if @chat_rooms.any? %>
    <%= render @chat_rooms %>
  <% else %>
    <p class="text-muted">You don't have any started chat yet</p>
  <% end %>
</ul>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%- if @chat_room.errors.any? %>
  <div class="alert alert-danger">
    <h4 class="alert-heading">Oh No!</h4>
    <p>Something went wrong</p>
  </div>
<% end %>

<%= render 'form' %>

app/views/chat_rooms/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1><%= @chat_room.title %></h1>
    </div>
    <div class="col">
      <%= link_to 'Edit chat', edit_chat_room_path(@chat_room), class: 'btn btn-primary pull-xs-right'%>
      <button type="button" class="btn btn-info pull-xs-right" data-toggle="modal" data-target="#myModal">Show participants</button>
      <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h3 class="modal-title">Participants</h3>
            </div>
            <div class="modal-body">
              <ul>
                <% @chat_room.participants.each do |user| %>
                  <li>
                    <%= image_tag user.user.avatar.url(:thumb) %> <%= online_status user.user %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
  <%= render @chat_room.messages %>
</div>

<%= form_for @message, url: '#' do |f| %>
  <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
    <small class="text-muted">From 2 to 1000 characters</small>
  </div>

  <div class="container">
    <div class="row">
      <div class="col">
        <%= f.submit 'Post', class: 'btn btn-primary btn-lg', id: 'button_send' %>
      </div>
      <div class="col">
        <%= link_to 'Leave',
                    participant_path(@chat_room),
                    method: :delete,
                    class: 'btn btn-danger pull-xs-right',
                    data: {confirm: 'Are you sure?'} %>
      </div>
    </div>
    </div>
  </div>

    <script type="text/javascript" charset="utf-8">

      $('#message_body').keyup(function(event){
        if(event.keyCode === 13){
          $('#button_send').click();
        }
      });

      function sendBye() {
        $('#message_body').append("Just left the chat");
        $('#button_send').click();
      }

      $(document).on('confirm:complete', function (e, answer) {
        if (answer) {
          sendBye();
        }
      });

    </script>
<% end %>