config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :chat_rooms, only: [:new, :create, :show, :index, :update, :edit, :destroy]

  resources :users, only: [:index]

  resources :participants, only: [:create, :destroy]

  resources :charts, only: [:index]

  resources :charts, only: [] do
    collection do
      get 'users_by_chat'
      get 'popular_users'
      get 'current_day_messages'
    end
  end

  #post 'participants' => 'participants#create', as: :create_participant

  mount ActionCable.server => '/cable'

  root 'chat_rooms#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CableChat</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<nav class="navbar navbar-dark bg-inverse">
  <%= link_to 'CableChat', root_path, class: 'navbar-brand' %>

    <ul class="nav navbar-nav pull-xs-right">
      <% if user_signed_in? %>
        <% if current_user.admin %>
          <li class="nav-item active">
            <%= link_to 'Site Stats', charts_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Admin Panel', rails_admin_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item active">
          <%= link_to 'Users', users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <span class="text-muted">Logged in as <strong><%= current_user.name %></strong></span>
        </li>
        <li class="nav-item">
          <%= image_tag current_user.avatar.url(:thumb) %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Account', edit_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link'  %>
        </li>
      <% end %>
    </ul>

</nav>

<div class="container">

  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>

</div>

<footer>
  <div class="container">
    <p class="text-muted">Created by <%= link_to 'Ilya Bodrov', 'http://bodrovis.tech' %> | Modified by <%= link_to 'Federico Chiappero', 'https://www.linkedin.com/in/federico-chiappero-04595292' %></p>
  </div>
</footer>
</body>
</html>